# Usa nano docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: scomputacion_vue_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - scomputacion-net

  web:
    image: nginx:alpine
    container_name: scomputacion_vue_nginx
    restart: always
    ports:
      - "8080:80"  # Usamos el 8081 para probar sin romper nada existente
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - scomputacion-net

  db:
    image: postgres:14
    container_name: scomputacion_vue_db
    restart: always
    environment:
      POSTGRES_DB: taller
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # IMPORTANTE: Aqu√≠ montamos tu copia de datos
      - ./postgres_data_legacy:/var/lib/postgresql/data
    networks:
      - scomputacion-net

networks:
  scomputacion-net:
    driver: bridge
